version: '0.9'
emailToList: "kasung@wso2.com"
infrastructureConfig:
  iacProvider: KUBERNETES
  infrastructureProvider: GKE
  containerOrchestrationEngine: None
  includes:
    - CentOS-7.5
    - MySQL-5.7
    - OPEN_JDK8
  provisioners:
    - name: kubernetes infra provision
      description: Provision Infra for running intg tests
      remoteRepository: "git@github.com:kasunbg/testgrid-sample-workspace.git"
      remoteBranch: k8s
      scripts:
        - name: 'Kubernetes-namespace-isolation-provisioner'
          type: KUBERNETES
          phase: CREATE
        - name: 'Delete-kubernetes-namespace'
          type: KUBERNETES
          phase: DESTROY
deploymentConfig:
  deploymentPatterns:
    - name: 'deployment'
      remoteRepository: "git@github.com:kasunbg/testgrid-sample-workspace.git"
      remoteBranch: k8s
      description: 'deployment of the resources in the gke'
      scripts:
        - name: 'wso2am-k8s-yaml-generator'
          type: SHELL
          file: deploymentRepository/wso2am.sh
          
        - name: 'wso2am-k8s-deployment'
          type: KUBERNETES
          inputParameters:
            yamls: 'deployment.yaml'
            deployments: 'wso2apim-with-analytics-apim'
scenarioConfigs:
  - testType: TESTNG
    remoteRepository: "https://github.com/wso2/product-apim.git"
    remoteBranch: "product-scenarios"
    name: "apim-scenarios"
    description: "apim-scenarios"
    file: product-scenarios/test.sh
    inputParameters:
      RemoteProductDir: "<find-the-proper-path-in-k8s-env>/usr/lib/wso2/wso2am/2.6.0/wso2am-2.6.0"
